language: python
python:
  - "2.7"
  - "3.3"

sudo: false

addons:
  apt:
    packages:
      - git
      - libtool
      - autoconf
      - automake

before_install:
  - pushd libsecp256k1
  - ./autogen.sh
  - ./configure --enable-module-recovery --enable-module-ecdh --enable-module-schnorr --enable-experimental --disable-tests
  - make
  - popd
  - virtualenv ENV
  - source ENV/bin/activate
  - pip install -U pip setuptools cffi coverage coveralls

install:
  - python setup.py -q install

script:
  - LD_LIBRARY_PATH=./libsecp256k1/.libs coverage run --source=secp256k1 setup.py pytest

after_success:
  - coveralls
